### ISSUE TITLE
Create maven configuration to automate deployment to OSSRH

### ISSUE THREAD

**Issue by forgedhallpass** [OWASP/www-project-csrfguard#12]
To current way of creating a new release:

```ps1
# the artifacts must be signed using gpg
mvn clean verify -Prelease-sign-artifacts
# prepare the release locally
mvn release:clean release:prepare
# perform the release after making sure that everything looks as expected
mvn release:perform
# push the release
git push origin master
# push the newly created tag
git push origin <tag_name>
```

The contents of the _settings.xml_:
```xml
<settings>
	<servers>
		<server>
		<id>ossrh</id>
		<username>JIRA_USER_WITH_PERMISSIONS</username>
		<password>JIRA_PASSWORD</password>
		</server>
	</servers>
	<profiles>
		<profile>
			<id>ossrh</id>
			<activation>
			<activeByDefault>true</activeByDefault>
			</activation>
			<properties>
				<gpg.passphrase>PERSONAL_GPG_PASSPHRASE</gpg.passphrase>
			</properties>
		</profile>
	</profiles>
</settings>
```

**Comment by forgedhallpass** [comment]
Related commit fa60e72e5727d408e9d6777c41f437dcbd82f07e

**Comment by aramrami** [comment]
You have all permission now. So I can close this issue.

**Comment by forgedhallpass** [comment]
> 
> 
> You have all permission now. So I can close this issue.

The issue was marked as an "enhancement" and was assigned to me. It is a good practice and desired to have commits assigned to issues. Next time please DO NOT close issues that are still in progress, I will do when I feel pleased with the results.

p.s. after a few hours of you closing the issue, the released seem to have succeeded and the version [4.0.0](https://search.maven.org/search?q=csrfguard) is available on the maven central repository.

**Comment by aramrami** [comment]
I open this issue.

**Comment by forgedhallpass** [comment]
Released version is available on the maven central repository:
https://search.maven.org/artifact/org.owasp/csrfguard-parent/4.0.0/pom
