### ISSUE TITLE
Why csrfguard creates so many Tomcat sessions?

### ISSUE THREAD

**Issue by iacarlos** [OWASP/www-project-csrfguard#14]
Why csrfguard creates so many Tomcat sessions?

The Tomcat application is configured with the legacy unique per-session model. After the application is started from Tomcat manager (https://localhost/manager/html), I open the application with the browser and open several jsp pages. Instantanly hundreds of sessions are created and they can see at Tomcat manager panel. Each session with only an attribute ARC_CSRFTOKEN and its value like this one as an example: UNVH-ICE1-N9Q2-9BU2-7GWQ-R250-OT93-QMYA

If I navigate the same pages with another web explorer, then no more session are created. It's like the sessions with the token attribute are shared between different users.

Is this the normal behaviour? My concern is that this could be an anormal session creation

Thanks in advance

**Comment by forgedhallpass** [comment]
Hello @iacarlos,

Please provide the versions (CSRFGuard, Tomcat), configurations and steps to reproduce the issue.

Thanks

**Comment by iacarlos** [comment]
I use this version:
		
        <dependency>
        	<groupId>org.owasp</groupId>
			<artifactId>csrfguard</artifactId>
			<version>3.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.owasp.esapi</groupId>
			<artifactId>esapi</artifactId>
			<version>2.1.0</version>
		</dependency>

**Tomcat**
Apache Tomcat/9.0.10	

**Java**
1.8.0_181-b13

org.owasp.csrfguard.ValidateWhenNoSessionExists = true
org.owasp.csrfguard.ProtectedMethods=POST,PUT,DELETE,GET 
org.owasp.csrfguard.TokenPerPage=false
org.owasp.csrfguard.TokenPerPagePrecreate=false
org.owasp.csrfguard.Rotate=false
org.owasp.csrfguard.Ajax=true
org.owasp.csrfguard.Protect=true
org.owasp.csrfguard.action.Rotate=org.owasp.csrfguard.action.Rotate
org.owasp.csrfguard.TokenName=ARC-CSRFTOKEN
org.owasp.csrfguard.SessionKey=ARC_CSRFTOKEN
org.owasp.csrfguard.JavascriptServlet.injectIntoForms = true
org.owasp.csrfguard.JavascriptServlet.injectGetForms = true
org.owasp.csrfguard.JavascriptServlet.injectFormAttributes = true
org.owasp.csrfguard.JavascriptServlet.injectIntoAttributes = true

org.owasp.csrfguard.protected.a_page=a_page.jsp

Steps
1. Restart Tomcat. 87 sessions are created instantanly
2. Some application navigation. Sessions are increased to 540
3. More navigation. Sessions increase to 1955
4. Sessions quantity does not increase more. But neither they are decreased. Sessions quantity get stabilized at that value

![01_Tomcat_just_after_Tomcat_restart](https://user-images.githubusercontent.com/83410019/116568613-e7e04800-a908-11eb-9096-6b96e03f30a7.png)
![02_sessions_Tomcat_just_after_Tomcat_restart](https://user-images.githubusercontent.com/83410019/116568616-e878de80-a908-11eb-82d6-0c87d0b39de9.png)
![03_a_Tomcat_session_just_after_Tomcat_restart](https://user-images.githubusercontent.com/83410019/116568621-e9117500-a908-11eb-8b98-d3d234436d76.png)
![04_Tomcat_after_some_applicatio_navigation](https://user-images.githubusercontent.com/83410019/116568626-e9aa0b80-a908-11eb-865b-d384255c5839.png)

**Comment by forgedhallpass** [comment]
The latest official version of CSRFGuard is 4.0.0 which includes significant changes in the project architecture, new features, bug fixes, optimizations etc. The enhancements also enable custom session handling (e.g. support for stateless web applications) logic.

Please update to the latest version and let me know if the issue persists.

You can also check out/do some preliminary analysis on the test application included in the project.

**Comment by forgedhallpass** [comment]
Since you haven't provided any update, the issue will be closed. If the problem will persist in the new version as well, then it can be re-opened.
