### ISSUE TITLE
Documentation: csrfguard.properties improvement

### ISSUE THREAD

**Issue by jellisgwn** [OWASP/www-project-csrfguard#15]
The following text in `csrfguard.properties` could be cleaned up and more concise:

```
# Note: Rotation in case of AJAX requests is not currently not supported because of the possible race conditions.
# A Single Page Application can fire multiple simultaneous requests. If rotation is enabled,
# the first request might trigger a token change before the validation of the same token within the second request,
# causing false-positive CSRF intrusion exceptions.
```

"is *not* currently *not* supported"

The sentence starting "If rotation is enabled, ..." could be clearer, "If rotation were enabled for AJAX requests, the first request could trigger..."

Happy to provide a PR if it would be helpful.

**Comment by forgedhallpass** [comment]
hello @jellisgwn,

Thanks for pointing it out; there are multiple sections indeed that could use some re-working in the future. Feel free to provide a PR and will accept it.
