### ISSUE TITLE
3.1.0 release code here is different to the 3.1.0 jar in Maven Central

### ISSUE THREAD

**Issue by trigfoot** [OWASP/www-project-csrfguard#16]
There are quite a few differences between the 3.1.0 release here and the 3.1.0 release in Maven Central. Do you think the current 3.1.0 release here on GitHub should be changed to a newer 3.x version number to avoid confusion and possibly publish it to Maven Central under that new version? Thanks.

![mavenCentral3 1 0VsGitHub3 1 0](https://user-images.githubusercontent.com/10706037/119001690-1e4b3900-b984-11eb-939e-a0bafea3097b.png)

**Comment by forgedhallpass** [comment]
Hello @trigfoot,

Thanks for pointing this out. I have created a GitHub release with the previous state of the code for historical reasons, but I did not intend to release it "officially" to the Maven central. 

The only officially supported version from now on is 4.0.0, so I'd recommend you to upgrade.
