### ISSUE TITLE
how to reload properties file in the server ?

### ISSUE THREAD

**Issue by elbadsi** [OWASP/www-project-csrfguard#18]
when i change the value of tokenLength in properties file , it doesn't take the value that I put !!

**Comment by forgedhallpass** [comment]
Hello @elbadsi,

I've just checked, and the functionality is working as expected.

![image](https://user-images.githubusercontent.com/13679401/124098496-450d8c80-da65-11eb-8cd9-f8a8e5e1734a.png)

If you are using the

`org.owasp.csrfguard.configuration.provider.factory=org.owasp.csrfguard.config.overlay.ConfigurationOverlayProviderFactory`

then you need to restart the server after modifying the configurations. In this case it is recommended to make your changes in the overlay properties file, to leave the original configurations intact.

If for some reason, you'd like to modify the configurations on the fly, then you'll have to use the

`org.owasp.csrfguard.config.overlay.ConfigurationAutodetectProviderFactory`,

although I don't currently see why would someone need this.

You can clone the repository and use the included test application to play around. You can find the details on the README page.

**Comment by forgedhallpass** [comment]
When creating a ticket, please use the provided issue templates.
