### ISSUE TITLE
request through a proxyPass problem

### ISSUE THREAD

**Issue by stefano-1973** [OWASP/www-project-csrfguard#255]
As explained in the pull-request #254, the library fails with a web server served by a proxyPass. The user receives this message: "a OWASP CSRFGuard JavaScript was included from within an unauthorized domain".
More details in the pull request. 

(Excuse me if the pull request was enough and this ticket useless)

**Comment by forgedhallpass** [comment]
Hello @stefano-1973,

Thank you for pointing this out and for contributing to improving the code.
I've left some minor comments in the PR, once those are changed I'll merge it.
With regards to the ticket, this is the expected procedure. Ticket first, then an associated PR.
