### ISSUE TITLE
unecessary character ' * ' in the index.md

### ISSUE THREAD

**Issue by shubhangi013** [OWASP/www-project-csrfguard#26]
The index.md and subsequently https://owasp.org/www-project-csrfguard/  have a ' * '
![Screenshot from 2021-10-03 02-51-41](https://user-images.githubusercontent.com/78342516/135732209-22af501b-37b8-44ae-9847-cc7c2b6293cf.png)

 which makes one think there's a condition there but I think there isn't any and it's a case of typo.

**Comment by aramrami** [comment]
Fixed.

**Comment by shubhangi013** [comment]
I opened a PR for this 😅
