### ISSUE TITLE
Location of .tld file

### ISSUE THREAD

**Issue by rameshkt** [OWASP/www-project-csrfguard#276]
I have integrated CSRF Guard into a Grails 6.2.0 application. The csrfguard.tld file is not recognised. Is it possible to have the file in META-INF/ instead of META-INF/tags? The tld scan pattern in grails does not look into sub-directories of META-INF. As of now I have created custom tags for the same set of tags in the .tld file. And the application works fine.
Regards

**Comment by aramrami** [comment]
Hello
Please submit a merge request and I will approve it.

Thanks
Azzeddine RAMRAMI

**Comment by rameshkt** [comment]
@aramrami Created a request #277. Hope it is correct.

**Comment by forgedhallpass** [comment]
Closed by #277
