### ISSUE TITLE
add the code of conduct

### ISSUE THREAD

**Issue by shubhangi013** [OWASP/www-project-csrfguard#28]
**Is your feature request related to a problem? Please describe.**
There isn't any code of conduct file unlike att the other OWASP web repositories 

**Describe the solution you'd like**
Add a CODE_OF_CONDUCT.md.

**Describe alternatives you've considered**
none

**Additional context**
I'd like to work on this issue so please assign me this.

**Comment by aramrami** [comment]
I mean the OWASP code of conduct. So no need to a specific file.  I will add a link to OWASP code of conduct.

**Comment by shubhangi013** [comment]
Oh alright!

**Comment by aramrami** [comment]
I will close this issue. Thanks for your help

**Comment by aramrami** [comment]
I add a reference to OWASP Code Of Conduct in index.md file.
