### ISSUE TITLE
IE11 error: startsWith not supported

### ISSUE THREAD

**Issue by stefano-1973** [OWASP/www-project-csrfguard#35]
The normalizeUrl and calculatePageTokenForUri functions in csrfguard.js use a function not supported by IE11: startsWith
For example in the js file there is this:

let normalizedUrl = url.startsWith('/') ? url : '/' + url;

I see that you have already created the function startsWith(s, prefix) but you have not used it in the above instruction (and other places)

**Comment by forgedhallpass** [comment]
https://github.com/OWASP/www-project-csrfguard/issues/31 would also solve this issue implicitly.

**Comment by stefano-1973** [comment]
I've created the pull request #158 for this issue

**Comment by forgedhallpass** [comment]
Thanks @stefano-1973. Congrats for your first contribution!

Thinking out loud, I believe polyfills would have been another viable solution. The `console.debug`s should rather be removed through minification and the generated JS should be used in production instead, but this will be handled in #31 then.
