### ISSUE TITLE
Migrate and update documentation

### ISSUE THREAD

**Issue by stefano-1973** [OWASP/www-project-csrfguard#36]
In OWASP-CSRFGuard/csrfguard/src/main/resources/csrfguard.properties this link
https://www.owasp.org/index.php/CSRFGuard_3_Token_Injection
is not valid. The page doesn't exists anymore and reditect to https://owasp.org/www-project-csrfguard/

May be at the moment can be substituted with https://wiki.owasp.org/index.php/CSRFGuard_3_Token_Injection (waiting for a 4.0 updated page)?

P.S.: the documentation to the usage of the 4.x library doesn't exists and also the old documentation of 3.1.0 has been removed (the page doesn't exist anymore using the old link http://www.owasp.org/index.php/CSRFGuard-3- Configuration). If someone want the old documentation it can be found here: https://wiki.owasp.org/index.php/CSRFGuard_3_User_Manual

**Comment by forgedhallpass** [comment]
Hello @stefano-1973

Thank you for creating the ticket. Indeed, currently the only relevant documentation for `4.x` can be found in the `readme.md` page and the `csrfguard.properties` file.

p.s. We also welcome contributions if you would consider doing so.

**Comment by forgedhallpass** [comment]
![image](https://user-images.githubusercontent.com/13679401/142184136-022667bf-5384-4828-bdb5-b4962d902c77.png)

The [OWASP Wiki](https://wiki.owasp.org) has been archived. The documentation should be moved to https://owasp.org/www-project-csrfguard, which is generated from markdown files available in this repository.

**Comment by HimanshHK** [comment]
Sir, I wanted to resolve this. Can you please assign me this.

**Comment by forgedhallpass** [comment]
> Sir, I wanted to resolve this. Can you please assign me this.

Thank you @HimanshHK. The ticket is now assigned to you.

**Comment by forgedhallpass** [comment]
@HimanshHK  any updates?

**Comment by Atharva-Kanherkar** [comment]
Hi @forgedhallpass is there any help needed? I'd like to start working on the documentation if needed.

**Comment by forgedhallpass** [comment]
@Atharva-Kanherkar please feel free to start working on the documentation. Contributions are welcome!

**Comment by forgedhallpass** [comment]
Closed by #272
