### ISSUE TITLE
Inaccurate Properties Printout

### ISSUE THREAD

**Issue by LPmaverick** [OWASP/www-project-csrfguard#54]
**Describe the bug**
The printout of my configurations is not completely accurate to what I have configured, specifically the JavaScriptServlet configs.  Though the configurations are being respected during testing.  Meaning that if I set injectGetForms to true this is working as intended; if I set it to false, that too works.  I do not utilize configuring these within web.xml, everything is via the properties file in my app's WEB-INF folder.

**To Reproduce**
My test app is a Websphere app.  Here is the config file I am using to test.
[csrfguard.txt](https://github.com/OWASP/www-project-csrfguard/files/7951793/csrfguard.txt)

**Expected behavior**
CSRFGuard 3.x printing is accurate.

**Screenshots**
Printing properties before JavaScript servlet, note, the JavaScript properties might not be initialized yet: 
OWASP CSRFGuard properties
************************************************************
* Actions: 
	* org.owasp.csrfguard.action.Redirect
		* Parameter: Page = /CG4xWeb/error.html
	* org.owasp.csrfguard.action.Log
		* Parameter: Message = potential cross-site request forgery (CSRF) attack thwarted (user:%user%, ip:%remote_ip%, method:%request_method%, uri:%request_uri%, error:%exception_message%)
* Ajax: true
* Enabled: true
* Force Synchronous Ajax: false
* Is Javascript Inject Into Dynamically Created Nodes: false
* Javascript Domain Strict: false
* Javascript Inject Form Attributes: false
* Javascript Inject Get Forms: false
* Javascript Inject Into Attributes: false
* Javascript Inject Into Forms: false
* Javascript Params Initialized: false
* Javascript Referer Match Domain: false
* Javascript Referer Match Protocol: false
* Logical Session Extractor: org.owasp.csrfguard.session.SessionTokenKeyExtractor
* New Token Landing Page: /CG4xWeb/home
* Page Token Synchronization Tolerance: 2000 ms
* Print Config: true
* Prng: java.security.SecureRandom(algorithm: SHA1PRNG, provider: IBMJCE version 1.8)
* Protect: false
* Rotate: false
* Token Holder: org.owasp.csrfguard.token.storage.impl.InMemoryTokenHolder
* Token Length: 32
* Token Name: OWASP-CSRFTOKEN
* Token Per Page: false
* Token Per Page Precreate: false
* Unprotected Pages: 
	* /CG4xWeb/static/*
	* /CG4xWeb/home
	* /CG4xWeb/error.html
	* /CG4xWeb/JavaScriptServlet
* Use New Token Landing Page: true
* Validation When No Session Exists: true
* ************************************************************

Printing properties after JavaScript servlet, note, the javascript properties have now been initialized: 
OWASP CSRFGuard properties
************************************************************
* Actions: 
	* org.owasp.csrfguard.action.Redirect
		* Parameter: Page = /CG4xWeb/error.html
	* org.owasp.csrfguard.action.Log
		* Parameter: Message = potential cross-site request forgery (CSRF) attack thwarted (user:%user%, ip:%remote_ip%, method:%request_method%, uri:%request_uri%, error:%exception_message%)
* Ajax: true
* Enabled: true
* Force Synchronous Ajax: false
* Is Javascript Inject Into Dynamically Created Nodes: false
* Javascript Domain Strict: false
* Javascript Inject Form Attributes: false
* Javascript Inject Get Forms: false
* Javascript Inject Into Attributes: false
* Javascript Inject Into Forms: false
* Javascript Params Initialized: false
* Javascript Referer Match Domain: false
* Javascript Referer Match Protocol: false
* Logical Session Extractor: org.owasp.csrfguard.session.SessionTokenKeyExtractor
* New Token Landing Page: /CG4xWeb/home
* Page Token Synchronization Tolerance: 2000 ms
* Print Config: true
* Prng: java.security.SecureRandom(algorithm: SHA1PRNG, provider: IBMJCE version 1.8)
* Protect: false
* Rotate: false
* Token Holder: org.owasp.csrfguard.token.storage.impl.InMemoryTokenHolder
* Token Length: 32
* Token Name: OWASP-CSRFTOKEN
* Token Per Page: false
* Token Per Page Precreate: false
* Unprotected Pages: 
	* /CG4xWeb/static/*
	* /CG4xWeb/home
	* /CG4xWeb/error.html
	* /CG4xWeb/JavaScriptServlet
* Use New Token Landing Page: true
* Validation When No Session Exists: true
************************************************************

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 97.0.1072.69

**Comment by forgedhallpass** [comment]
Hello @LPmaverick,

Printing the information happens through reflection, hence if you are saying that the solution works properly, the only thing I can imagine to cause this misalignment, would be some weird concurrency issue.

I haven't yet confirmed/reproduced the problem, but you are welcome to create a PR with a fix, and I'll review it.

**Comment by LPmaverick** [comment]
The thing is, CSRFGuard 3.x printed the configurations accurately.  So, what changed that would cause some of the configurations to print correctly and others not to?

This printout is fairly critical in helping teams with their app's configurations.

**Comment by forgedhallpass** [comment]
> So, what changed that would cause some of the configurations to print correctly and others not to?

The project has been **heavily** refactored and improved since `3.x`. 

> This printout is fairly critical in helping teams with their app's configurations.

Currently you are the first and only one who faced/reported this issue.

You can view the changes and navigate the history, since this is an open-source project. 

Starting point:

https://github.com/OWASP/www-project-csrfguard/blob/b5fa6c8bb8b7b5277f5b46fb7c9a05ae8034acfe/csrfguard/src/main/java/org/owasp/csrfguard/CsrfGuard.java#L265

As mentioned above, the `toString()` method, now uses reflection to view the configuration data, instead of doing it "manually".

**Comment by LPmaverick** [comment]
My applications are legacy J2EE apps running in WebSphere.  Perhaps that has something to do with it?  I also wonder if others pay as close attention to the printout, or even utilize the printout.

**Comment by forgedhallpass** [comment]
I've did a little debugging, and the issue is reproducible. The problem is that even though the message states the JavaScript configurations were initialized, this is not the case, hence the reflection logic shows the un-initialized values.

**Comment by forgedhallpass** [comment]
The JavaScript configuration parameters were initialized after the printout, at first access. This is why the application worked correctly, and only the printout contained outdated values. The printout in `3.x` used getters to retrieve the configuration data, and those implicitly invoked the initialization logic.

The issue should be fixed in dcb0e9a

**Comment by LPmaverick** [comment]
Sweet!  I look forward to the next release. Thank you.

**Comment by forgedhallpass** [comment]
@LPmaverick version [`4.1.2`](https://github.com/OWASP/www-project-csrfguard/releases/tag/4.1.2) has been released and it should soon appear on the maven central as well.
