### ISSUE TITLE
Ability to extend CsrfGuardFilter

### ISSUE THREAD

**Issue by deepak229** [OWASP/www-project-csrfguard#8]
We have a scenario where we want to skip CSRF guard evaluation based on some parameters in the request. It could be authentication mechanism or any other. 
CsrfGuardFilter is a final class and so cannot be extended to write our custom logic before the filter is being evaluated. Thus, 
Requesting to make it a non-final class so that we can extend to add custom logic before the filter logic gets executed.

**Comment by deepak229** [comment]
@forgedhallpass, I created a new Issue her based on your comment on: https://github.com/aramrami/OWASP-CSRFGuard/issues/152
I dont think I have permission to create a branch and create a pull request on this repo. It would be great if you can make the changes as per the request in this issue. 

Thank you.

**Comment by aramrami** [comment]
Only me and @forgedhallpass have the full admin right. We will look to your issue.

**Comment by forgedhallpass** [comment]
Created pull-requests that have an issue assigned will be accepted or declined based on an analysis done by the project admins. In this case the issue was fixed by the associated commit.
